export const FILTERS = [{
    name: 'orgs',
    key: 'orgTypeID',
    label: '组织类型',
    valueKey: 'orgID',
    labelKey: 'orgName',
}, {
    name: 'brands',
    key: 'brandID',
    label: '品牌',
    valueKey: 'brandID',
    labelKey: 'brandName',
    callserver: 'getShopBrand',
    callparams: {},
}, {
    name: 'shopCategories',
    key: 'shopCategoryID',
    label: '门店组',
    valueKey: 'shopCategoryID',
    labelKey: 'shopCategoryName',
    callserver: 'getShopBrand',
    callparams: {},
}, {
    name: 'citys',
    key: 'cityID',
    label: '城市',
    valueKey: 'cityID',
    labelKey: 'cityName',
    callserver: 'getShopCities',
    callparams: {},
}, {
    name: 'tags',
    key: 'tagNames',
    label: '标签',
    valueKey: 'tagNames',
    labelKey: 'tagName',
},
//  {
//     name: 'tags',
//     key: 'disRoute',
//     label: '配送线路',
//     valueKey: 'tagID',
//     labelKey: 'tagName',
// }
];
