
export { default as MyActivities } from './SaleCenterNEW/MyActivities/MyActivities';
export { default as MySpecialActivities } from './SpecialPromotionNEW/MySpecialActivities/index';
export { default as GiftInfo } from './GiftNew/GiftInfo/index';
export { default as MyActivitiesShop } from './SaleCenterNEW/MyActivities/MyActivitiesShop';
export { default as SaleCenterNEWShop } from './SaleCenterNEW/indexShop';
export { default as WeChatMallPromotionCreate } from './WeChatMall/AddNew';
export { default as WeChatMallPromotionList } from './WeChatMall/PromotionList';
export { default as MessageTemplatesPage } from './BasicSettings/SmsSettingPage';
export { default as WeChatMessageSettingPage } from './BasicSettings/WeChatMessageSettingPage';
export { default as NewCustomerPage } from './NewCreatePromotions/NewCustomerPage';
export { default as NewSaleActivityPage } from './NewCreatePromotions/NewSaleActivityPage';
export { default as NewOnSaleActivityPage } from './NewCreatePromotions/NewOnSaleActivityPage';
export { default as RepeatPromotionPage } from './NewCreatePromotions/RepeatPromotionPage';
export { default as SalePromotionPage } from './NewCreatePromotions/SalePromotionPage';
export { default as LoyaltyPromotionPage } from './NewCreatePromotions/LoyaltyPromotionPage';
export { default as FansInteractivityPage } from './NewCreatePromotions/FansInteractivityPage';
export { default as OnlinePromotionPage } from './NewCreatePromotions/OnlinePromotionPage';
export { default as ShareRules } from './ShareRules/index';
export { default as ShareRulesOld } from './ShareRulesOld/index';
export { default as PromotionCalendar } from './PromotionCalendar';
export { default as WeChatCouponManagementList } from './WeChatCouponManagement';
export { default as ThirdCouponPage } from './ThirdCoupon';
export { default as ZhiFuBaoCouponList } from './ZhiFuBaoCouponManagement';
export { default as CouponManageList } from './ThirdCoupon/CouponManage/CouponManageList';
export { default as WeChatCouponCreate } from './WeChatCouponManagement/WeChatCouponCreate';
export { default as TrdPromotionInterface } from './TrdPromotionInterface';
export { default as PromotionCalendarNew } from './PromotionCalendarNew';
export { default as PromotionDecoration } from './PromotionDecoration';
export { default as CreateActive } from './SaleActives/CreateActive';
export { default as PromotionList } from './WeChat2Mall/PromotionList'
export { default as LanchChannelList } from './LanchChannel/index'
export { default as CreateActiveTwo } from './SaleActives/CreateActiveTwo';
export { default as GiftDetails } from './GiftNew/GiftDetails/index'//礼品使用详情
