export const COLUMNS = [
            {
                title:'状态',
                dataIndex:'giftStatus',
                key:'giftStatus',
                className:'x-tc',
            },{
                title:'已制卡',
                dataIndex:'createdNum',
                key:'createdNum',
                className:'x-tr',
            },{
                title:'已售出',
                dataIndex:'soldNum',
                key:'soldNum',
                className:'x-tr',
            },{
                title:'已充值',
                dataIndex:'rechargedNum',
                key:'rechargedNum',
                className:'x-tr',
            },{
                title:'已作废',
                dataIndex:'cancelledNum',
                key:'cancelledNum',
                className:'x-tr',
            },{
                title:'总计',
                dataIndex:'totalSum',
                key:'totalSum',
                className:'x-tr',
            }
        ];
